#!/bin/bash
# build.sh - Master Build Dispatcher
# Generated by LLM Cross-Compiler Framework
#
# Decides which build backend to use based on Hardware and Task.

set -euo pipefail

WORK_DIR="${BUILD_CACHE_DIR:-/build-cache}"
OUTPUT_DIR="${WORK_DIR}/output"
mkdir -p "$OUTPUT_DIR"

# Inputs injected by Orchestrator
TASK="${MODEL_TASK:-LLM}"           # LLM, VOICE, VLM
SOC="${TARGET_BOARD:-Generic}"      # e.g. RK3588, RK3566
QUANT="${QUANTIZATION:-FP16}"

echo "=== Build Dispatcher ==="
echo "Target SoC: $SOC"
echo "Task Type:  $TASK"
echo "Quant Mode: $QUANT"

# --- DISPATCH LOGIC ---

if [[ "$SOC" == *"rk3588"* ]] || [[ "$SOC" == *"RK3588"* ]]; then
    # === ROCKCHIP RK3588 (Powerful NPU) ===
    if [ "$TASK" == "LLM" ]; then
        echo ">> Strategy: RK3588 detected. Using RKLLM-Toolkit for NPU acceleration."
        /app/modules/rkllm_module.sh
    else
        echo ">> Strategy: Non-LLM task ($TASK). Using RKNN-Toolkit2."
        /app/modules/rknn_module.sh
    fi

elif [[ "$SOC" == *"rk3566"* ]] || [[ "$SOC" == *"RK3566"* ]]; then
    # === ROCKCHIP RK3566 (Weaker NPU) ===
    if [ "$TASK" == "LLM" ]; then
        echo ">> Strategy: RK3566 detected. NPU too weak for RKLLM. Fallback to CPU (llama.cpp)."
        # Fallback: Standard GGUF conversion
        python3 /app/scripts/convert_hf_to_gguf.py "$MODEL_SOURCE" --outtype q8_0
    else
        echo ">> Strategy: Voice/Vision task. Using RKNN-Toolkit2 for NPU acceleration."
        /app/modules/rknn_module.sh
    fi

else
    # === GENERIC / UNKNOWN ===
    echo ">> Strategy: Generic/Unknown Target. Using CPU (llama.cpp)."
    # Placeholder for standard CPU build
    echo "Running standard CPU build..."
fi

# --- PACKAGING ---
echo "=== Packaging Artifacts ==="
cd "$OUTPUT_DIR" && tar -czf "deployment_${SOC}_${TASK}.tar.gz" *
echo "Build completed successfully."
