#!/bin/bash
# config_module.sh - Hardware Config & CMake Toolchain Generator
# Part of LLM Cross-Compiler Framework
# DIREKTIVE: Goldstandard, CCACHE-Enabled.

set -euo pipefail

# --- CONFIGURATION & GLOBALS ---
readonly SCRIPT_NAME="config_module.sh"
readonly BUILD_CACHE_DIR="${BUILD_CACHE_DIR:-/build-cache}"
readonly HARDWARE_CONFIG_FILE="${HARDWARE_CONFIG_FILE:-${BUILD_CACHE_DIR}/target_hardware_config.txt}"
readonly OUTPUT_TOOLCHAIN_FILE="${OUTPUT_TOOLCHAIN_FILE:-${BUILD_CACHE_DIR}/cross_compile_toolchain.cmake}"
readonly OUTPUT_CONFIG_FILE="${OUTPUT_CONFIG_FILE:-${BUILD_CACHE_DIR}/build_config.sh}"

declare -A HW_CONFIG
declare -A COMPILER_CONFIG

# --- LOGGING ---
log_info() { echo "ℹ️  [$(date '+%H:%M:%S')] [CONFIG] $1"; }
log_success() { echo "✅ [$(date '+%H:%M:%S')] [CONFIG] $1"; }
log_warn() { echo "⚠️  [$(date '+%H:%M:%S')] [CONFIG] $1"; }
log_error() { echo "❌ [$(date '+%H:%M:%S')] [CONFIG] $1" >&2; }

die() { log_error "$1"; exit 1; }

# ... [Hardware Config Loading - Standard Template Logic] ...
load_hardware_config() {
    log_info "Lade Hardware-Konfiguration..."
    if [[ -f "$HARDWARE_CONFIG_FILE" ]]; then
        while IFS='=' read -r key value; do
            [[ "$key" =~ ^[[:space:]]*# ]] && continue
            [[ -z "$key" ]] && continue
            key=$(echo "$key" | tr -d ' \t')
            value=$(echo "$value" | tr -d ' \t' | sed 's/^"//;s/"$//')
            HW_CONFIG["$key"]="$value"
        done < <(grep -E '^[^#]*=' "$HARDWARE_CONFIG_FILE")
    else
        log_warn "Config nicht gefunden, nutze Defaults."
        HW_CONFIG[ARCHITECTURE_FULL]="[ARCHITEKTUR]"
    fi
}

# ============================================================================
# CMAKE TOOLCHAIN GENERATION (MIT CCACHE)
# ============================================================================

generate_cmake_toolchain() {
    log_info "Generiere CMake Toolchain: $OUTPUT_TOOLCHAIN_FILE"
    
    # CCACHE Detection
    local ccache_path=$(which ccache || echo "")
    
    cat > "$OUTPUT_TOOLCHAIN_FILE" << EOF
# CMake Toolchain File - Generated by Template
SET(CMAKE_SYSTEM_NAME Linux)
SET(CMAKE_SYSTEM_PROCESSOR ${HW_CONFIG[ARCHITECTURE_FULL]})

# 1. ERSETZEN: Compiler Pfade für Ihre Architektur
# SET(CMAKE_C_COMPILER   /usr/bin/[CROSS]-gcc)
# SET(CMAKE_CXX_COMPILER /usr/bin/[CROSS]-g++)
EOF

    # CCACHE Integration
    if [[ -n "$ccache_path" ]]; then
        cat >> "$OUTPUT_TOOLCHAIN_FILE" << EOF

# CCACHE Configuration
SET(CMAKE_C_COMPILER_LAUNCHER "$ccache_path")
SET(CMAKE_CXX_COMPILER_LAUNCHER "$ccache_path")
EOF
        log_info "CCACHE aktiviert: $ccache_path"
    fi

    cat >> "$OUTPUT_TOOLCHAIN_FILE" << EOF

# Compiler Flags
SET(CMAKE_C_FLAGS   "\${CMAKE_C_FLAGS} -O3")
SET(CMAKE_CXX_FLAGS "\${CMAKE_CXX_FLAGS} -O3")

# Build settings
SET(CMAKE_BUILD_TYPE Release)
SET(BUILD_SHARED_LIBS OFF)
EOF
    log_success "Toolchain generiert."
}

generate_build_config() {
    log_info "Generiere Build Config Script..."
    cat > "$OUTPUT_CONFIG_FILE" << EOF
#!/bin/bash
export TARGET_ARCH="${HW_CONFIG[ARCHITECTURE_FULL]}"
export CMAKE_TOOLCHAIN_FILE="$OUTPUT_TOOLCHAIN_FILE"
export BUILD_JOBS=$(nproc)
EOF
    chmod +x "$OUTPUT_CONFIG_FILE"
}

main() {
    load_hardware_config
    generate_cmake_toolchain
    generate_build_config
    log_success "Konfiguration abgeschlossen."
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then main "$@"; fi
