#!/bin/bash
# rkllm_module.sh Template
# Generated by LLM Cross-Compiler Framework
#
# ZWECK: Wrapper für RKLLM-Toolkit (LLM Quantisierung auf RK3588/RK3576).
# INSTALLIERT das Python-Wheel automatisch vor der Nutzung.

set -euo pipefail

# ============================================================================
# ENVIRONMENT
# ============================================================================

MODEL_SOURCE="${MODEL_SOURCE:-}"
QUANTIZATION="${QUANTIZATION:-w8a8}"
BUILD_CACHE_DIR="${BUILD_CACHE_DIR:-/build-cache}"
OUTPUT_DIR="${OUTPUT_DIR:-${BUILD_CACHE_DIR}/output}"
SCRIPT_DIR="/app/scripts"
RKLLM_DIR="/app/rknn-llm"

# Logging
log_info() { echo ">> [RKLLM-Module] $(date '+%H:%M:%S') INFO: $1"; }
log_error() { echo ">> [RKLLM-Module] $(date '+%H:%M:%S') ERROR: $1" >&2; }
die() { log_error "$1"; exit 1; }

# ============================================================================
# HELPER
# ============================================================================

ensure_rkllm_installed() {
    if python3 -c "import rkllm" &> /dev/null; then
        return 0
    fi
    
    log_info "Installing RKLLM Python package..."
    # Suche wheel im 'packages' Unterordner
    WHEEL_FILE=$(find "$RKLLM_DIR" -name "rkllm_toolkit*.whl" | head -n 1)
    
    if [[ -z "$WHEEL_FILE" ]]; then
        die "No RKLLM wheel found in $RKLLM_DIR/packages/."
    fi
    
    pip install "$WHEEL_FILE" || die "Pip install failed."
}

# ============================================================================
# MAIN LOGIC
# ============================================================================

main() {
    log_info "Initializing RKLLM Pipeline..."

    # 1. Validierung
    if [[ -z "$MODEL_SOURCE" ]]; then die "MODEL_SOURCE not set."; fi
    if [[ ! -d "$MODEL_SOURCE" ]]; then die "MODEL_SOURCE must be a directory."; fi

    # 2. Quantisierung Mapping
    case "${QUANTIZATION}" in
        "w8a8"|"W8A8"|"INT8"|"Q8_0") Q_TYPE="w8a8" ;;
        "w4a16"|"W4A16"|"INT4"|"Q4_K_M") Q_TYPE="w4a16" ;;
        *) log_info "Defaulting to 'w8a8'."; Q_TYPE="w8a8" ;;
    esac

    # 3. Target Platform
    TARGET_PLATFORM="rk3588"
    if [[ "${TARGET_BOARD:-}" == *"3576"* ]]; then TARGET_PLATFORM="rk3576"; fi

    # 4. Toolkit Setup (Clone)
    if [ ! -d "$RKLLM_DIR" ]; then
        log_info "Cloning RKLLM Toolkit..."
        REPO_URL="${RKLLM_TOOLKIT_REPO_OVERRIDE:-https://github.com/airockchip/rknn-llm.git}"
        git clone "$REPO_URL" "$RKLLM_DIR" || die "Clone failed."
    fi

    # 5. Install Wheel (NEU)
    ensure_rkllm_installed

    # 6. Python Script Call
    CONVERTER="$SCRIPT_DIR/export_rkllm.py"
    if [ ! -f "$CONVERTER" ]; then die "Converter script missing."; fi
    
    MODEL_NAME=$(basename "$MODEL_SOURCE")
    OUTPUT_FILE="$OUTPUT_DIR/${MODEL_NAME}_${TARGET_PLATFORM}_${Q_TYPE}.rkllm"
    
    log_info "Converting..."
    
    set +e
    python3 "$CONVERTER" \
        --model "$MODEL_SOURCE" \
        --output "$OUTPUT_FILE" \
        --quant "$Q_TYPE" \
        --target "$TARGET_PLATFORM"
    
    if [ $? -eq 0 ] && [ -f "$OUTPUT_FILE" ]; then
        log_info "✅ Success: $OUTPUT_FILE"
    else
        die "Conversion failed."
    fi
}

main "$@"
